services:
  - type: web
    name: dog-backend
    env: python
    buildCommand: ""
    startCommand: waitress-serve --port=$PORT app:app
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_NAME
        value: dogbreed_db
      - key: DB_USER
        value: doguser
      - key: DB_PASSWORD
        value: dogpass
      - key: DB_PORT
        value: 5432
